-- CONSTITUENT
CREATE TABLE CONSTITUENT (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    FIRSTNAME NVARCHAR(100),
    LASTNAME NVARCHAR(100),
    TYPE NVARCHAR(50) -- 'Individual' or 'Organization'
);

-- ADDRESS
CREATE TABLE ADDRESS (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    CONSTITUENTID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES CONSTITUENT(ID),
    STREET NVARCHAR(200),
    CITY NVARCHAR(100),
    STATE NVARCHAR(50),
    ZIP NVARCHAR(20)
);

-- REVENUE
CREATE TABLE REVENUE (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    CONSTITUENTID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES CONSTITUENT(ID),
    REVENUE_TYPE_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES REVENUE_TYPE(ID),
    AMOUNT MONEY,
    DATE_RECEIVED DATE
);

-- INTERACTION
CREATE TABLE INTERACTION (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    CONSTITUENTID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES CONSTITUENT(ID),
    INTERACTION_TYPE_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES INTERACTION_TYPE(ID),
    DATE_OCCURRED DATE,
    NOTES NVARCHAR(MAX)
);

-- EVENT
CREATE TABLE EVENT (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    EVENT_CATEGORY_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES EVENT_CATEGORY(ID),
    NAME NVARCHAR(200),
    EVENT_DATE DATE,
    LOCATION NVARCHAR(200)
);