-- REVENUE_TYPE
CREATE TABLE REVENUE_TYPE (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    NAME NVARCHAR(100) -- e.g., 'Donation', 'Grant', 'Membership'
);

-- INTERACTION_TYPE
CREATE TABLE INTERACTION_TYPE (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    NAME NVARCHAR(100) -- e.g., 'Phone Call', 'Email', 'Meeting'
);

-- EVENT_CATEGORY
CREATE TABLE EVENT_CATEGORY (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    NAME NVARCHAR(100) -- e.g., 'Fundraiser', 'Volunteer', 'Conference'
);